### ISSUE TITLE
System tray minimalism

### ISSUE THREAD

**Issue by baimafeima** [DreamDevel/eRadio#18]
Is your software capable of being accessed via the system tray (similar to radiotray-ng) and if no, do you have any plans to implement such a GUI option?

**Comment by geocool** [comment]
Hello, sorry for the late answer, I wasn't keeping an eye on eRadio project for a while and for some reason github didn't notified me for the issue :) 

No I'm not planning to create a system tray feature. I have plans for several features when I have time but not this ones :)
