### ISSUE TITLE
Don't have "for elementary OS" in your appdata

### ISSUE THREAD

**Issue by danrabbit** [DreamDevel/eRadio#25]
https://github.com/DreamDevel/eRadio/blob/35b661e011de97ba58b955c4a0cda42dc3c871c5/data/com.github.dreamdevel.eradio.appdata.xml#L7

Since everything published in AppCenter is "for elementary OS", this is redundant

**Comment by geocool** [comment]
Fixed 3465cdd3d23f860fbe89e032e156e4ff9fc8bb24
